// Build is for this Giter8 template

Global / onChangedBuildSource := ReloadOnSourceChanges


/*
 * These variables are used for the generation of GitHub Action workflows; the
 * workflows are used to verify that a generated Scala 3 sbt project is valid.
 *
 * The following workflow files:
 *
 *    ./github/workflows/ci.yml
 *    ./github/workflows/clean.yml
 *
 * were generated by invoking:
 *
 *    sbt githubWorkflowGenerate
 *
 * from within THIS project directory.
 */
ThisBuild / githubWorkflowPublishTargetBranches := Nil
ThisBuild / githubWorkflowScalaVersions := scalaVersions
ThisBuild / githubWorkflowJavaVersions := javaVersions
ThisBuild / githubWorkflowBuild := Seq(
  // Creates a sbt project and runs tests in ./project/giter8.test
  WorkflowStep.Sbt(
    name = Some("sbt Project: Create"),
    commands = List("g8Test")
  ),
  // Tests and runs the created sbt project
  WorkflowStep.Run(
    name = Some("sbt Project: Test & Run"),
    commands = List(
      s"pushd target/sbt-test/${templateName}/scripted",
      "sbt test run",
      "popd"
    )
  )
)


/*
 * This command alias runs the tests provided in ./project/giter8.test, which
 * are used to locally verify the correctness of a generated sbt project.
 */
addCommandAlias("test", "g8Test")


lazy val scala212 = "2.12.17"
lazy val scalaVersions = Seq(scala212)
lazy val javaVersions = Seq("8", "11", "17").map(JavaSpec.temurin)
lazy val templateName = "scala3-template"


lazy val root = project.in(file("."))
  .settings(
    scalaVersion := scala212, // MUST use this scala version (for now)
    name := templateName,
    scriptedLaunchOpts ++= Seq(
      "-Xms1024m",
      "-Xmx1024m",
      "-XX:ReservedCodeCacheSize=128m",
      "-Xss2m",
      "-Dfile.encoding=UTF-8"
    ),
    crossScalaVersions := scalaVersions
  )
