/*
 * The keys set here are for the generation of GitHub Action workflows; the
 * workflows are used to verify that a generated Scala 3 sbt project template
 * is valid.
 *
 * The following workflow files:
 *
 *    ./github/workflows/ci.yml
 *    ./github/workflows/clean.yml
 *
 * were generated by invoking:
 *
 *    sbt githubWorkflowGenerate
 *
 * from within the root (the only) project of this build.
 */

import Utils._

lazy val workflowProjectName = "workflow-test-project"

ThisBuild / githubWorkflowTargetBranches := Seq("main")
ThisBuild / githubWorkflowPublishTargetBranches := Nil
ThisBuild / githubWorkflowScalaVersions := scalaVersions
ThisBuild / githubWorkflowJavaVersions := javaVersions
ThisBuild / githubWorkflowBuild := Seq(
  WorkflowStep.Sbt(
    name=Some("Create/Test/Run Scala 3 sbt Project Template: Local"),
    commands=List("g8Test")
  ),
  WorkflowStep.Run(
    name=Some(
      "Create/Test/Run Scala 3 sbt Project Template: Import (from THIS Repo)"
    ),
    commands=List(
      /*
       * The `${{ github.repository }}` string ensures that the current (THIS)
       * repository is used for the workflow; the `++${{ matrix.scala }}` string
       * NEEDED to be manually included.
       */
      "sbt ++${{ matrix.scala }} new ${{ github.repository }} " +
        s"--name=${workflowProjectName}",
      s"pushd ${workflowProjectName}",
      "sbt test run",
      "popd"
    )
  )
)
